Areas/Admin/Controllers/AboutController.cs
using AspNetMvcPersonalWebSite.Data;
using AspNetMvcPersonalWebSite.Models.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcPersonalWebSite.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class AboutController : Controller
    {
        private readonly AppDbContext _db;

        //AboutRepository repository = new AboutRepository();

        public AboutController(AppDbContext db)
        {
            _db = db;
        }


        public IActionResult Index()
        {
            var list = _db.About.ToList();

            return View(list);
        }


        public IActionResult Edit(int id)
        {
            var edit = _db.About.Find(id);
            if (edit != null)
            {
                return View(edit);
            }
            return RedirectToAction("Index");

        }


        [HttpPost]
        public IActionResult Edit(About about)
        {
            if (ModelState.IsValid)
            {
                var aboutDb = _db.About.Find(about.Id);
                if (aboutDb != null)
                {
                    aboutDb.Name = about.Name;
                    aboutDb.Surname = about.Surname;
                    aboutDb.Adress = about.Adress;
                    aboutDb.Phone = about.Phone;
                    aboutDb.Mail = about.Mail;
                    aboutDb.Description = about.Description;

                    _db.SaveChanges();

                    return RedirectToAction("Index");
                }

            }
            ViewBag.message = "Hata";
            return RedirectToAction("Index", ViewBag.message);
        }


        public ActionResult Delete(int Id)
        {
            var delete = _db.About.Find(Id);
            if (delete != null)
            {
                _db.About.Remove(delete);

                _db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            //var newPerson = new About();

            return View();
        }

        [HttpPost]
        public IActionResult Create(About about)
        {
            if (about.Name != null)
            {
                _db.About.Add(about);

                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }
    }
}

Controllers/AuthController.cs
using AspNetMvcPersonalWebSite.Data;
using AspNetMvcPersonalWebSite.Models.Entity;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AspNetMvcPersonalWebSite.Controllers
{
    public class AuthController : Controller
    {
        private readonly AppDbContext _db;

        public AuthController(AppDbContext db)
        {
            _db = db;
        }


        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(Admin? admin, string? returnUrl)
        {
            if (ModelState.IsValid)
            {
                var user = _db.Admin.FirstOrDefault(e => e.Mail == admin.Mail && e.Password == admin.Password);

                if (user != null)
                {
                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.NameIdentifier,admin.Id.ToString()),
                        new Claim(ClaimTypes.Email,admin.Mail),
                        new Claim(ClaimTypes.Name,"Jerfi Ali")
                    };


                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    var claimsPrinciple = new ClaimsPrincipal(claimsIdentity);

                    var properties = new AuthenticationProperties
                    {
                        IsPersistent = user.RememberMe,
                        ExpiresUtc = DateTime.UtcNow.AddDays(1)
                    };

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrinciple, properties);

                    return Redirect(returnUrl != null ? returnUrl : "/");
                }

            }
            ModelState.AddModelError(string.Empty, "Email or password is incorrect!");

            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return Redirect("/");
        }

    }
}

Controllers/ContactController.cs
using AspNetMvcPersonalWebSite.Data;
using AspNetMvcPersonalWebSite.Models.Entity;
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcPersonalWebSite.Controllers
{
    public class ContactController : Controller
    {
        private readonly AppDbContext db;

        public ContactController(AppDbContext Db)
        {
            db = Db;
        }


        public IActionResult ContactMe()
        {
            //var contact = new Contact();
            return View();
        }

        [HttpPost]
        public IActionResult ContactMe(Contact contact)
        {
            contact.Tarih = DateTime.Parse(DateTime.Now.ToString());

            db.Contact.Add(contact);

            db.SaveChanges();

            ViewBag.Message = "Mesajınız başarıyla gönderildi";
            return View();
        }


    }
}

Controllers/PersonalController.cs
using AspNetMvcPersonalWebSite.Data;
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcPersonalWebSite.Controllers
{
    public class PersonalController : Controller
    {
        private readonly AppDbContext db;

        public PersonalController(AppDbContext Db)
        {
            db = Db;
        }


        public IActionResult Education()
        {
            var educations = db.Education.ToList();            
            return View(educations);
        }
        
        public IActionResult Skills()
        {
            var skills = db.Skills.ToList();

            return View(skills);
        }
        
        public IActionResult Hobbies()
        {
            var hobbies = db.Interests.ToList();

            return View(hobbies);
        }
        
        public IActionResult Certification()
        {
            var certification = db.Certification.ToList();

            return View(certification);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Resume - Start Bootstrap Theme</title>
    <link rel="icon" type="image/x-icon" href="~/assets/img/profile.jpg" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/997a8bee10.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles.css" rel="stylesheet" />
</head>
<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">
            <span class="d-block d-lg-none">Jerfi Ali Uçar</span>
            <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-square mx-auto mb-2" src="~/assets/img/JAU.jpeg" alt="" /></span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link js-scroll-trigger" asp-controller="Home" asp-action="Index">HAKKIMDA</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" asp-controller="Home" asp-action="Experience">PROJELER</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" asp-controller="Personal" asp-action="Education">EĞİTİM</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" asp-controller="Personal" asp-action="Skills">BECERİLER</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" asp-controller="Personal" asp-action="Hobbies">HOBİ / İLGİ ALANLARIM</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" asp-controller="Personal" asp-action="Certification">SERTİFİKALAR</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" asp-controller="Contact" asp-action="ContactMe">İLETİŞİM</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" asp-area="Admin" asp-controller="About" asp-action="Index">ADMIN PANEL</a></li>
                

                @if (Context.User.Identity.IsAuthenticated)
                {                    
                    <li class="nav-item"><a class="nav-link" asp-controller="Auth" asp-action="Logout">Çıkış Yap</a></li>

                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Giriş Yap</a>
                    </li>
                }
            </ul>



        </div>
    </nav>
    <!-- Page Content-->

    <div class="container-fluid p-0">
        <!-- About-->
        <!-- Experience-->
        <!-- Education-->
        <!-- Skills-->
        <!-- Interests-->
        <!-- Awards-->
        @RenderBody()

    </div>
    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/js/scripts.js"></script>
</body>
</html>