Models/Entity/Experience.cs
namespace AspNetMvcPersonalWebSite.Models.Entity
{
    public class Experience
    {
        public int Id { get; set; }

        public string? Title { get; set; }

        public string? SubTitle { get; set; }

        public string? Description { get; set; }

        public string? Tarih { get; set; }

        public string? Link { get; set; }    
    }
}

Areas/Admin/Controllers/ExperienceController.cs
using AspNetMvcPersonalWebSite.Data;
using AspNetMvcPersonalWebSite.Models.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcPersonalWebSite.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class ExperienceController : Controller
    {
        private readonly AppDbContext _db;

        public ExperienceController(AppDbContext db)
        {
            _db = db;
        }


        public IActionResult Index()
        {
            var list = _db.Experience.ToList();

            return View(list);
        }


        public IActionResult Edit(int id)
        {
            var edit = _db.Experience.Find(id);
            if (edit != null)
            {
                return View(edit);
            }
            return RedirectToAction("Index");

        }


        [HttpPost]
        public IActionResult Edit(Experience experience)
        {
            if (ModelState.IsValid)
            {
                var experienceDb = _db.Experience.Find(experience.Id);
                if (experienceDb != null)
                {
                   experienceDb.Title=experience.Title;
                    experienceDb.SubTitle=experience.SubTitle;
                    experienceDb.Description=experience.Description;
                    experienceDb.Tarih=experience.Tarih;

                    _db.SaveChanges();

                    return RedirectToAction("Index");
                }

            }
            ViewBag.message = "Hata";
            return RedirectToAction("Index", ViewBag.message);
        }


        public ActionResult Delete(int Id)
        {
            var delete = _db.Experience.Find(Id);
            if (delete != null)
            {
                _db.Experience.Remove(delete);

                _db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Experience experience)
        {
            if (experience.Title != null)
            {
                _db.Experience.Add(experience);

                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }
    }
}

Areas/Admin/Views/Experience/Create.cshtml
<h2 class="mb-5">Create New </h2>

<form asp-area="Admin" asp-controller="Experience" asp-action="Create" method="post">

    <label class="form-label">Title</label>
    <input type="text" name="Title" class="form-control" required>
    <br />

    <label class="form-label">SubTitle</label>
    <input type="text" name="Subtitle1" class="form-control" required>
    <br />

    <label class="form-label">Açıklama</label>
    <input type="text" name="Description" class="form-control" required>
    <br />

    <label class="form-label">Tarih</label>
    <input type="text" name="Tarih" class="form-control" required>
    <br />

    <button class="btn btn-primary">Save</button>

</form>

Areas/Admin/Views/Experience/Edit.cshtml
@model Experience

<h2 class="mb-5">Edit Form</h2>
<form asp-area="Admin" asp-controller="Experience" asp-action="Edit" method="post">

    <label class="form-label">Title</label>
    <input type="text" asp-for="Title" name="Title" class="form-control" required>
    <br />

    <label class="form-label">Alt Başlık</label>
    <input type="text" asp-for="SubTitle" name="SubTitle" class="form-control" required>
    <br />

    <label class="form-label">Açıklama</label>
    <input type="text" asp-for="Description" name="Description" class="form-control" required>
    <br />

    <label class="form-label">Tarih</label>
    <input type="text" asp-for="Tarih" name="Tarih" class="form-control" required>
    <br />

    <button class="btn btn-primary">Save</button>

</form>

Areas/Admin/Views/Experience/Index.cshtml
@model List<Experience>

<h2 class="mt-3">Deneyim Bilgileri</h2>
<div class="mt-4" style="padding-left:unset">

    <span class="text-danger">@ViewBag.message</span>
    <table class="table table-dark  table-striped-columns">
        <thead>
            <tr>
                <th>ID</th>
                <th>Başlık</th>
                <th>Alt Başlık</th>
                <th>Açıklama</th>
                <th>Tarih</th>
            </tr>
        </thead>
        @foreach (Experience item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Title</td>
                <td>@item.SubTitle</td>
                <td>@item.Description</td>
                <td>@item.Tarih</td>

                <td>
                    <a asp-area="Admin" asp-controller="Experience" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Düzenle</a>

                    <a asp-area="Admin" asp-controller="Experience" asp-action="Delete" asp-route-id="@item.Id" class="btn-danger btn">Sil</a>
                </td>
            </tr>

        }
    </table>
    <div>
        <a asp-area="Admin" asp-controller="Experience" asp-action="Create" class="btn btn-primary"> Create New </a>
    </div>

</div>