Models/Entity/Education.cs
namespace AspNetMvcPersonalWebSite.Models.Entity
{
    public class Education
    {
        public int Id { get; set; }

        public string? Title { get; set; }

        public string? SubTitle1 { get; set; }

        public string? SubTitle2 { get; set; }

        public string? GNO { get; set; }

        public string? Tarih { get; set; }



    }
}

Areas/Admin/Controllers/EducationController.cs
using AspNetMvcPersonalWebSite.Data;
using AspNetMvcPersonalWebSite.Models.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcPersonalWebSite.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class EducationController : Controller
    {
        private readonly AppDbContext _db;

        public EducationController(AppDbContext db)
        {
            _db = db;
        }


        public IActionResult Index()
        {
            var list = _db.Education.ToList();

            return View(list);
        }


        public IActionResult Edit(int id)
        {
            var edit = _db.Education.Find(id);
            if (edit != null)
            {
                return View(edit);
            }
            return RedirectToAction("Index");

        }


        [HttpPost]
        public IActionResult Edit(Education education)
        {
            if (ModelState.IsValid)
            {
                var educationDb = _db.Education.Find(education.Id);
                if (educationDb != null)
                {
                    educationDb.Title = education.Title;
                    educationDb.SubTitle1 = education.SubTitle1;
                    educationDb.SubTitle2 = education.SubTitle2;
                    educationDb.Tarih = education.Tarih;
                    educationDb.GNO = education.GNO;

                    _db.SaveChanges();

                    return RedirectToAction("Index");
                }

            }
            ViewBag.message = "Hata";
            return RedirectToAction("Index", ViewBag.message);
        }


        public ActionResult Delete(int Id)
        {
            var delete = _db.Education.Find(Id);
            if (delete != null)
            {
                _db.Education.Remove(delete);

                _db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public IActionResult Create()
        { 
            return View();
        }

        [HttpPost]
        public IActionResult Create(Education about)
        {
            if (about.Title != null)
            {
                _db.Education.Add(about);

                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }
    }
}

Areas/Admin/Views/Education/Create.cshtml
<h2 class="mb-5">Create New </h2>

<form asp-area="Admin" asp-controller="Education" asp-action="Create" method="post">

    <label class="form-label">Title</label>
    <input type="text" name="Title" class="form-control" required>
    <br />

    <label class="form-label">SubTitle</label>
    <input type="text" name="Subtitle1" class="form-control" required>
    <br />

    <label class="form-label">SubTitle 2</label>
    <input type="text" name="SubTitle2" class="form-control" required>
    <br />

    <label class="form-label">GNO</label>
    <input type="number" name="GNO" placeholder="Genel Not Ortalaması" class="form-control" required>
    <br />

    <label class="form-label">Tarih</label>
    <input type="text" name="Tarih" class="form-control" required>
    <br />

    <button class="btn btn-primary">Save</button>

</form>

Areas/Admin/Views/Education/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Areas/Admin/Views/Education/Edit.cshtml
@model Education

<h2 class="mb-5">Edit Form</h2>
<form asp-area="Admin" asp-controller="Education" asp-action="Edit" method="post">

    <label class="form-label">Title</label>
    <input type="text" asp-for="Title" name="Title" class="form-control" required>
    <br />

    <label class="form-label">Alt Başlık</label>
    <input type="text" asp-for="SubTitle1" name="SubTitle" class="form-control" required>
    <br />

    <label class="form-label">Alt Başlık 2</label>
    <input type="text" asp-for="SubTitle2" name="SubTitle2" class="form-control">
    <br />

    <label class="form-label">GNO</label>
    <input type="number" asp-for="GNO" name="GNO" placeholder="Genel Not Ortalaması" class="form-control" required>
    <br />

    <label class="form-label">Tarih</label>
    <input type="text" asp-for="Tarih" name="Tarih" class="form-control" required>
    <br />

    <button class="btn btn-primary">Save</button>

</form>

Areas/Admin/Views/Education/Index.cshtml
@model List<Education>

<h2 class="mt-3">Eğitim Bilgileri</h2>
<div class="mt-4" style="padding-left:unset">

    <span class="text-danger">@ViewBag.message</span>
    <table class="table table-dark  table-striped-columns">
        <thead>
            <tr>
                <th>ID</th>
                <th>Başlık</th>
                <th>Alt Başlık</th>
                <th>Alt Başlık 2</th>
                <th>GNO</th>
                <th>Tarih</th>
            </tr>
        </thead>
        @foreach (Education item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Title</td>
                <td>@item.SubTitle1</td>
                <td>@item.SubTitle2</td>
                <td>@item.GNO</td>
                <td>@item.Tarih</td>

                <td>
                    <a asp-area="Admin" asp-controller="Education" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Düzenle</a>

                    <a asp-area="Admin" asp-controller="Education" asp-action="Delete" asp-route-id="@item.Id" class="btn-danger btn">Sil</a>
                </td>
            </tr>

        }
    </table>
    <div>
        <a asp-area="Admin" asp-controller="Education" asp-action="Create" class="btn btn-primary"> Create New </a>
    </div>

</div>