Models/Entity/Interests.cs
namespace AspNetMvcPersonalWebSite.Models.Entity
{
    public class Interests
    {
        public int Id { get; set; }

        public string? Description1 { get; set; }
        
        public string? Description2 { get; set; }
    }
}

Areas/Admin/Controllers/InterestsController.cs
using AspNetMvcPersonalWebSite.Data;
using AspNetMvcPersonalWebSite.Models.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcPersonalWebSite.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class InterestsController : Controller
    {
        private readonly AppDbContext _db;

        public InterestsController(AppDbContext db)
        {
            _db = db;
        }


        public IActionResult Index()
        {
            var list = _db.Interests.ToList();

            return View(list);
        }


        public IActionResult Edit(int id)
        {
            var edit = _db.Interests.Find(id);
            if (edit != null)
            {
                return View(edit);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit(Interests interests)
        {
            if (ModelState.IsValid)
            {
                var interestsDb = _db.Interests.Find(interests.Id);
                if (interestsDb != null)
                {
                    interestsDb.Description1 = interests.Description1;
                    interestsDb.Description2 = interests.Description2;

                    _db.SaveChanges();

                    return RedirectToAction("Index");
                }

            }
            ViewBag.message = "Hata";
            return RedirectToAction("Index", ViewBag.message);
        }


        public ActionResult Delete(int Id)
        {
            var delete = _db.Interests.Find(Id);
            if (delete != null)
            {
                _db.Interests.Remove(delete);

                _db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Interests interests)
        {
            if (interests.Description1 != null)
            {
                _db.Interests.Add(interests);

                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }
    }
}

Areas/Admin/Views/Interests/Create.cshtml
<h2 class="mb-5">Create New </h2>

<form asp-area="Admin" asp-controller="Interests" asp-action="Create" method="post">

    <label class="form-label">Açıklama</label>
    <textarea type="text" name="Description1" class="form-control" required></textarea>
    <br />

    <label class="form-label">Açıklama 2</label>
    <textarea type="text" name="Description2" class="form-control" required></textarea>
    <br />

    <button class="btn btn-primary">Save</button>

</form>

Areas/Admin/Views/Interests/Edit.cshtml
@model Interests

<h2 class="mb-5">Edit Form</h2>
<form asp-area="Admin" asp-controller="Interests" asp-action="Edit" method="post">

    <label class="form-label">Açıklama</label>
    <textarea type="text" asp-for="Description1" name="Description1" class="form-control"></textarea>
    <br />

    <label class="form-label">Açıklama 2</label>
    <textarea type="text" asp-for="Description2" name="Description2" class="form-control"> </textarea>
    <br />

    <button class="btn btn-primary">Save</button>

</form>

Areas/Admin/Views/Interests/Index.cshtml
@model List<Interests>

<h2 class="mt-3">Hobiler</h2>
<div class="mt-4" style="padding-left:unset">

    <span class="text-danger">@ViewBag.message</span>
    <table class="table table-dark  table-striped-columns">
        <thead>
            <tr>
                <th>ID</th>
                <th>Açıklama</th>
                <th>Açıklama 2</th>
            </tr>
        </thead>
        @foreach (Interests item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Description1</td>
                <td>@item.Description2</td>

                <td>
                    <a asp-area="Admin" asp-controller="Interests" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Düzenle</a>

                    <a asp-area="Admin" asp-controller="Interests" asp-action="Delete" asp-route-id="@item.Id" class="btn-danger btn">Sil</a>
                </td>
            </tr>
        }
    </table>
    <div>
        <a asp-area="Admin" asp-controller="Interests" asp-action="Create" class="btn btn-primary"> Create New </a>
    </div>

</div>